on:
  push:
    tags:
      - "*"
name: Publish Extension
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-18.04 # based on Buster Debian
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Create yarn cache folder
        run: |
          mkdir -p ~/yarn-cache
      - name: Yarn cache
        uses: actions/cache@v2
        with:
          path: ~/yarn-cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Package VSIX
        run: yarn run vsce package --yarn
      - name: Publish to Open VSX Registry
        run: |
          yarn run ovsx publish --pat '${{ secrets.OVSX_TOKEN }}' --packagePath *.vsix
      - name: Publish to Visual Studio Marketplace
        run: |
          yarn run vsce publish --pat '${{ secrets.VS_MARKETPLACE_TOKEN }}' --packagePath *.vsix
